# Generated by Django 4.2.1 on 2023-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidobservation',
            name='observation_date',
            field=models.DateField(),
        ),
    ]
