# Generated by Django 4.2.1 on 2023-05-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_tracker_app', '0004_alter_covidobservation_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidobservation',
            name='sequence_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
