# Generated by Django 4.2.1 on 2023-05-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_tracker_app', '0005_covidobservation_sequence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidobservation',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='covidobservation',
            name='sequence_number',
        ),
    ]
