# Generated by Django 4.2.1 on 2023-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_tracker_app', '0006_remove_covidobservation_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidobservation',
            name='confirmed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covidobservation',
            name='deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covidobservation',
            name='recovered',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
